baseURL = "http://localhost"
copyright = "Copyright © 2021"
title = "hugo-theme-gruvbox"
#paginate = 10
enableRobotsTXT = true

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      # This settings allows inlining <script> and <style> tags in markdown, 
      # which is useful and required to use Prism plugins, but may be dangerous 
      # if the content isn't trustworthy.
      unsafe = true

[imaging]
  # JPEG and WebP image processing quality, defaults to 75%
  #quality = 75

[params]
  # dark or light, defaults to light
  #defaultTheme = "light"
  # gray red green yellow blue purple aqua orange, defaults to blue
  #themeColor = "blue"
  # soft medium hard, defaults to medium
  #themeContrast = "medium"
  author = "Michael Schnerring"
  subtitle = "Theme Demo"
  description = "A retro-looking Hugo theme inspired by gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."

  [params.logo]
    text = "gruvbox"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]
  
  # By default, the theme creates resized versions of images ranging from 300 to
  # 700 pixels wide in increments of 100 pixels
  #[params.imageResize]
  #  min = 300
  #  max = 700
  #  increment = 100

  # Social share links for posts:
  #   - icon from the Simple Icons suite except "Email" from Tabler Icons
  #   - {url} is replaced with .Permalink
  #   - {title} is replaced with .Title
  # See also: https://github.com/bradvin/social-share-urls
  [[params.socialShare]]
    icon = "Facebook"
    formatString = "https://www.facebook.com/sharer.php?u={url}"
  [[params.socialShare]]
    icon = "Reddit"
    formatString = "https://reddit.com/submit?url={url}&title={title}"
  [[params.socialShare]]
    icon = "Twitter"
    formatString = "https://twitter.com/intent/tweet?url={url}&text={title}"
  [[params.socialShare]]
    icon = "LinkedIn"
    formatString = "https://www.linkedin.com/sharing/share-offsite/?url={url}"
  [[params.socialShare]]
    icon = "WhatsApp"
    formatString = "whatsapp://send/?text={title}%20{url}"
  [[params.socialShare]]
    icon = "Tumblr"
    formatString = "https://www.tumblr.com/widgets/share/tool?canonicalUrl={url}&title={title}&caption={title}"
  [[params.socialShare]]
    icon = "Pinterest"
    formatString = "http://pinterest.com/pin/create/button/?url={url}"
  [[params.socialShare]]
    icon = "YCombinator"
    formatString = "https://news.ycombinator.com/submitlink?u={url}&t={title}"
  [[params.socialShare]]
    icon = "VK"
    formatString = "http://vk.com/share.php?url={url}&title={title}&comment={title}"
  [[params.socialShare]]
    icon = "XING"
    formatString = "https://www.xing.com/spi/shares/new?url={url}"
  [[params.socialShare]]
    icon = "Telegram"
    formatString = "https://telegram.me/share/url?url={url}&text={title}"
  [[params.socialShare]]
    icon = "Mail"
    formatString = "mailto:?subject={title}&body={url}"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/blog"
    weight = 10
  [[menu.main]]
    identifier = "projects"
    name = "Projects"
    url = "/projects"
    weight = 20
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 30
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 40

[languages]
  [languages.en]
    languageName = "English"
    weight = 10
    [languages.en.params.jsonResume]
      present = "present"
  [languages.de]
    languageName = "Deutsch"
    weight = 20
    [languages.de.params.jsonResume]
      present = "heute"
