baseURL = "http://localhost"
copyright = "Copyright © 2021"
title = "hugo-gruvbox"
#paginate = 10

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # dark or light, defaults to light
  #defaultTheme = "dark"
  # gray red green yellow blue purple aqua orange, defaults to blue
  #themeColor = "blue"
  # soft medium hard, defaults to medium
  #themeContrast = "medium"
  author = "Michael Schnerring"
  subtitle = "Theme Demo"
  description = "A retro-looking Hugo theme inspired by gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."

  [params.logo]
    text = "hugo-gruvbox"
    url = "/"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]

  [params.bio]
    #avatarURL = "/avatar.jpg"
    description = "I love coding. I'm passionate about open-source and digital privacy. I like video games and CrossFit. I'm also terrible at blogging."

    [[params.bio.social]]
      icon = "github"
      URL = "https://github.com/schnerring"
      label = "schnerring"
    [[params.bio.social]]
      icon = "matrix"
      label = "@michael:schnerring.net"
    [[params.bio.social]]
      icon = "twitter"
      URL = "https://twitter.com/schnerringo"
    [[params.bio.social]]
      icon = "linkedin"
      URL = "https://www.linkedin.com/in/schnerring"
    [[params.bio.social]]
      icon = "stackoverflow"
      URL = "https://stackoverflow.com/users/1154965/michael-schnerring"

[menu]
  [[menu.main]]
    identifier = "blog"
    name = "Blog"
    url = "/"
    weight = 10
  [[menu.main]]
    identifier = "cv"
    name = "CV"
    url = "/cv"
    weight = 20
  [[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about"
    weight = 30
        
