baseURL = "http://localhost"
copyright = "Copyright © 2021"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # dark or light, defaults to light
  #defaultTheme = "dark"
  author = "Michael Schnerring"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]

  [params.bio]
    avatarURL = "a"
    description = "I love coding. I'm passionate about open-source and digital privacy. I like video games and CrossFit. I'm also terrible at blogging."

    [[params.bio.social]]
      icon = "github"
      URL = "https://github.com/schnerring"
      label = "schnerring"
    [[params.bio.social]]
      icon = "matrix"
      label = "@michael:schnerring.net"
    [[params.bio.social]]
      icon = "twitter"
      URL = "https://twitter.com/schnerringo"
    [[params.bio.social]]
      icon = "linkedin"
      URL = "https://www.linkedin.com/in/schnerring"
    [[params.bio.social]]
      icon = "stackoverflow"
      URL = "https://stackoverflow.com/users/1154965/michael-schnerring"


[languages]
  [languages.en]
    title = "hugo-gruvbox"
    subtitle = "Theme Demo"
    description = "A retro-looking Hugo theme inspired by gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."

    [languages.en.params.logo]
      text = "hugo-gruvbox"
      url = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
