baseURL = "http://localhost"
copyright = "Copyright © 2021"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
# dark or light, defaults to light
#defaultTheme = "dark"
author = "Michael Schnerring"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript",
      "bash",
      "diff",
      "toml"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard",
      "line-numbers",
      "command-line",
      "diff-highlight"
    ]


[languages]
  [languages.en]
    title = "hugo-gruvbox"
    subtitle = "Theme Demo"
    description = "A retro-looking Hugo theme inspired by gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."

    [languages.en.params.logo]
      text = "hugo-gruvbox"
      url = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"
