baseURL = "http://localhost"
copyright = "Copyright © 2021"

[build]
  writeStats = true

[languages]
  [languages.en]
    title = "hugo-gruvbox"
    subtitle = "Theme Demo"
    description = "A retro-looking Hugo theme inspired by gruvbox. The pastel colors are high contrast, easily distinguishable, pleasing to the eye, and feature light and dark color palettes."

    [languages.en.params.logo]
      text = "hugo-gruvbox"
      url = "/"

    [languages.en.menu]
      [[languages.en.menu.main]]
        identifier = "about"
        name = "About"
        url = "/about"

[params]
  # dark or light, defaults to light
  #defaultTheme = "dark"

  [params.prism]
    languages = [
      "markup",
      "css",
      "clike",
      "javascript"
    ]
    plugins = [
      "normalize-whitespace",
      "toolbar",
      "copy-to-clipboard"
    ]
    theme = "solarizedlight"

[module]
  replacements = "github.com/schnerring/hugo-gruvbox -> ../.."
  [[module.imports]]
    path = "github.com/schnerring/hugo-gruvbox"
  [[module.mounts]]
    source = "node_modules/prismjs"
    target = "assets/prismjs"
  [[module.mounts]]
    source = "node_modules/@tabler/icons/icons"
    target = "assets/tabler-icons"
  [[module.mounts]]
    source = "node_modules/simple-icons/icons"
    target = "assets/simple-icons"
  [[module.mounts]]
    source = "node_modules/typeface-ubuntu/files"
    target = "static/fonts"
  [[module.mounts]]
    source = "node_modules/typeface-ubuntu-mono/files"
    target = "static/fonts"
